### ISSUE TITLE
Items with same name all show same cover icon regardless of actual contents

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#32] opened 2015-10-08 03:47 UTC
All instances of an item with same name show the last retrieved cover icon regardless of what the first image actually was or if there even was an image. All cover icons are changed to the last cover image.

This may no longer be an issue if completed items are changed to final file name as this would prevent duplicate item references?

**Comment by pkrll** [comment] 2015-10-08 04:55
I can't recreate this problem, works for me. Though items with the same name can't be added to the list simultaneously (only if one of them is archived), which is a bug.

**Comment by mikemcduffie** [comment] 2015-10-08 07:27
More of a pain to replicate than I thought. I saw it twice in a row in testing and thought it was repeatable. In trying to find a thread that reproduces it repeatedly, but I haven't found the trigger. I'll keep trying to find a thread that works repeatedly, but something is happening with the 2.5.1 (03F1) build.

**Comment by mikemcduffie** [comment] 2015-10-08 18:40
I recreate it at will with 2.5.1 (043C). 

![screen shot 2015-10-08 at 11 38 07 am](https://cloud.githubusercontent.com/assets/4350221/10376142/2d6c818e-6db1-11e5-8d89-b36922cd9de9.png)

![screen shot 2015-10-08 at 11 38 32 am](https://cloud.githubusercontent.com/assets/4350221/10376148/31266056-6db1-11e5-9a1e-a0749f1867f1.png)

Interestingly the previous item(s) cover images changes before the compression is complete on the new item.

**Comment by pkrll** [comment] 2015-10-08 20:14
All right, now I understand. The problem is that I don't cache the images like before, instead it fetches them each them it updates the view from the folder. If you change the name of the folder and then add it to the list, the compressed items icon will disappear. I remember now why I did the cache thing from the beginning. It's an easy fix.

**Comment by pkrll** [comment] 2015-10-08 21:25
Fixed in latest build.

**Closed by pkrll** 2015-10-08 21:25 UTC
Labels: bug
